version: "3.7"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.1
    container_name: filebeat
    user: root
    # ELK 스택과 같은 네트워크에 조인
    networks:
      - elk
    restart: always

    volumes:
      # Filebeat 설정
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

      # 각 서버 로그 디렉터리(WSL2 경로) 마운트
      - /mnt/d/team5/server1-whisper/logs:/var/logs/whisper:ro
      - /mnt/d/team5/server2_rag/logs:/var/logs/server2_rag:ro
      - /mnt/d/team5/LLM_Insight_extraction/logs:/var/logs/llm_insight:ro
      - /mnt/d/team5/vector_search_server/logs:/var/logs/vector_search:ro
      - /mnt/d/team5/server2-report-generator/logs:/var/logs/report_generator:ro

networks:
  elk:
    external: true